# Generated by Django 3.0.5 on 2020-05-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200502_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
